export const data = [
  // motivation
  {
    id: 1,
    imgsrc: "/images/motivation.png",
    name: "motivation",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "motivation",
  },
  {
    id: 2,
    imgsrc: "/images/motivation1.png",
    name: "motivation1",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "motivation",
  },
  {
    id: 3,
    imgsrc: "/images/motivation2.png",
    name: "motivation2",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "motivation",
  },
  {
    id: 4,
    imgsrc: "/images/motivation3.png",
    name: "motivation3",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "motivation",
  },
  {
    id: 5,
    imgsrc: "/images/motivation4.jpg",
    name: "motivation4",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "motivation",
  },
  {
    id: 6,
    imgsrc: "/images/muhhamadali.jpg",
    name: "muhhamad ali",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "motivation",
  },

  // cars
  {
    id: 7,
    imgsrc: "/images/p1.jpg",
    name: "Porsche 911",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },
  {
    id: 8,
    imgsrc: "/images/f1.jpg",
    name: "F1",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },
  {
    id: 9,
    imgsrc: "/images/Charlesleclare.jpg",
    name: "Charlesleclare",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },
  {
    id: 10,
    imgsrc: "/images/Charlesleclarespecial.jpg",
    name: "Charlesleclare",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },
  {
    id: 11,
    imgsrc: "/images/FERRARIPoster.jpg",
    name: "FERRARI Poster",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },
  {
    id: 12,
    imgsrc: "/images/mustang.jpg",
    name: "Mustang",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },
  {
    id: 13,
    imgsrc: "/images/porsche.jpg",
    name: "Porsche",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },
  {
    id: 14,
    imgsrc: "/images/supra.png",
    name: "Supra",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "cars",
  },

  // players
  {
    id: 15,
    imgsrc: "/images/p2.jpg",
    name: "Messi",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "players",
  },
  {
    id: 16,
    imgsrc: "/images/p3.jpg",
    name: "CR7",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "players",
  },
  {
    id: 17,
    imgsrc: "/images/KingSalah.png",
    name: "King Salah",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "players",
  },
  {
    id: 18,
    imgsrc: "/images/LamineYamal.png",
    name: "Lamine Yamal",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "players",
  },
  {
    id: 19,
    imgsrc: "/images/messi.jpg",
    name: "Messi",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "players",
  },
  {
    id: 20,
    imgsrc: "/images/Mppape.jpg",
    name: "Mbappe",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "players",
  },
  {
    id: 21,
    imgsrc: "/images/p4.jpg",
    name: "Controller King",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "gaming",
  },
  {
    id: 22,
    imgsrc: "/images/ALAhly.jpg",
    name: "AL Ahly",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "players",
  },

  // anime
  {
    id: 23,
    imgsrc: "/images/animeonepiece.jpg",
    name: "One Piece",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "anime",
  },
  {
    id: 24,
    imgsrc: "/images/sukuna.jpg",
    name: "Sukuna",
    oldPrice: 250,
    newPrice: 200,
    count: 0,
    category: "anime",
  },
];
